---
version: "3.9"

services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    hostname: server-resilio
    restart: always
    volumes:
      - ${RESILIO_DATA}:/config
      - ${SHARED_DATA}:/sync
    ports:
      - 8888:8888
      - 55555:55555
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - server-shares

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: server-duplicati
    restart: always
    volumes:
      - ${DUPLICATI_DATA}:/config
      - ${DUPLICATI_BACKUPS}:/backups
      - ${SHARED_DATA}:/source:rod
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 8200:8200
    networks:
      - server-shares

  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    hostname: server-syncthing
    restart: always
    volumes:
      - ${SYNCTHING_DATA}:/config
      - ${SHARED_DATA}:/sync
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027"
    networks:
      - server-shares

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrower
    hostname: server-filebrowser
    restart: always
    volumes:
      - ${FILEBROWER_DATA}:/db
      - ${SHARED_DATA}:/srv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 10180:80
    networks:
      - server-shares

networks:
  server-shares:
