---
version: "3.9"

services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    hostname: server-resilio
    container_name: resilio-sync
    restart: always
    volumes:
      - ${DOCKER_DATA}/resilio_data:/config
      - ${PROJECT_DATA}:/sync/projects
      - ${SHARED_DATA}/ugreen:/sync/ugreen
    ports:
      # - 8888:8888
      - 55555:55555
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - server-backend

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    hostname: server-duplicati
    container_name: duplicati
    restart: always
    volumes:
      - ${DOCKER_DATA}/duplicati/config:/config
      - ${DUPLICATI_BACKUPS}:/backups
      - ${PROJECT_DATA}:/source/projects
      - ${SHARED_DATA}/ugreen:/source/ugreen
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    # ports:
    #   - 8200:8200
    networks:
      - server-backend

  syncthing:
    image: linuxserver/syncthing:latest
    hostname: server-syncthing
    container_name: syncthing
    restart: always
    volumes:
      - ${DOCKER_DATA}/syncthing/config:/config
      - ${PROJECT_DATA}:/sync/projects
      - ${SHARED_DATA}/ugreen:/sync/ugreen
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      # - 8384:8384
      - 22000:22000
      - 21027:21027
    networks:
      - server-backend

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrower
    hostname: server-filebrowser
    restart: always
    volumes:
      - ${DOCKER_DATA}/filebrower/data:/db
      - ${PROJECT_DATA}:/srv/projects
      - ${SHARED_DATA}/ugreen:/srv/ugreen
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 10180:80
    networks:
      - server-backend

networks:
  server-backend:
    external: true
